# TODO: Move to terraform
apiVersion: v1
kind: Service
metadata:
  name: balancer-service
spec:
  type: LoadBalancer
  selector:
    app: devex-2nd-ex-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000