apiVersion: v1
kind: Pod
metadata:
  name: kinesis-test
spec:
  containers:
  - name: kinesis-test
    image: amazonlinux:2
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    env:
    - name: AWS_REGION
      value: "us-east-1"